### ISSUE TITLE
[ERROR] 发生预期外的异常: Error: Not a valid V3 wallet

### ISSUE THREAD

**Issue by bitcoin-eth** [luoyeETH/autoFreeMint_pkg#1]
你好，报错[ERROR] 发生预期外的异常: Error: Not a valid V3 wallet是什么情况导致的，拜托解答谢谢

**Comment by luoyeETH** [comment]
应该是导入的keystore文件用的不是v3加密  
是不是第三方钱包导入的

**Comment by bitcoin-eth** [comment]
在配置文件中哪个条件填写的不对？可以麻烦告知一下吗，如何导入keystore文件使用v3加密

**Comment by luoyeETH** [comment]
按照流程应该不会有问题，第一次运行后会生成一个keystore的文件夹和一个privateKey.json的文件，在privateKey.json中填入私钥和密码，再次运行程序就会把私钥加密保存到keystore文件夹下面

**Comment by bitcoin-eth** [comment]
privatekey.json文件中太难写私钥是狐狸钱包的私钥和密码是吗

**Comment by bitcoin-eth** [comment]
大佬 可以加个微信不

**Comment by luoyeETH** [comment]
> privatekey.json文件中太难写私钥是狐狸钱包的私钥和密码是吗

私钥和要设置的密码。为了避免直接明文存私钥，所以做了一个加密，只有第一次运行的时候需要填私钥。或者直接使用第三方钱包的keystore导出

**Comment by luoyeETH** [comment]
> 大佬 可以加个微信不

ddddhm_luoye
